version: '3.8'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:80"
    depends_on:
      - socketio-server

  socketio-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "4000:4000"
